### ISSUE TITLE
Installation error with release 0.0.10

### ISSUE THREAD

**Issue by geschke** [Jamesits/pve-fake-subscription#14]
I tried to install the release 0.0.10 on a Proxmox Backup Server, but it did not work, here the complete console output:

```
root@pbs:~# ls
pve-fake-subscription_0.0.10+git-1_all.deb
root@pbs:~# dpkg -i pve-fake-subscription_0.0.10+git-1_all.deb 
Selecting previously unselected package pve-fake-subscription.
(Reading database ... 49126 files and directories currently installed.)
Preparing to unpack pve-fake-subscription_0.0.10+git-1_all.deb ...
Unpacking pve-fake-subscription (0.0.10+git-1) ...
Setting up pve-fake-subscription (0.0.10+git-1) ...
Created symlink /etc/systemd/system/timers.target.wants/pve-fake-subscription.timer → /lib/systemd/system/pve-fake-subscription.timer.
Activating Proxmox Backup Server...
Traceback (most recent call last):
  File "/usr/bin/pve-fake-subscription", line 136, in <module>
    activate_pbs(lic_pbs, "/etc/proxmox-backup/subscription")
  File "/usr/bin/pve-fake-subscription", line 116, in activate_pbs
    subscription = generate_subscription_pbs(key, [server_id], *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/pve-fake-subscription", line 99, in generate_subscription_pbs
    "url": url,
           ^^^
NameError: name 'url' is not defined
dpkg: error processing package pve-fake-subscription (--install):
 installed pve-fake-subscription package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 pve-fake-subscription

```

I downloaded the previous version 0.0.9, which was ok and installed correctly:

```
root@pbs:~# dpkg -i pve-fake-subscription_0.0.9+git-1_all.deb 
dpkg: warning: downgrading pve-fake-subscription from 0.0.10+git-1 to 0.0.9-1+git
(Reading database ... 49133 files and directories currently installed.)
Preparing to unpack pve-fake-subscription_0.0.9+git-1_all.deb ...
Unpacking pve-fake-subscription (0.0.9-1+git) over (0.0.10+git-1) ...
Setting up pve-fake-subscription (0.0.9-1+git) ...
Activating Proxmox Backup Server...
```

By the way, thanks for your package, it's great for running Proxmox on privately used servers!

Kind regards,
   Ralf

**Comment by Jamesits** [comment]
Fixed on 0.0.11, please have a try with the new version.
